#ifndef ___INANITY_INANITY_BASE_HPP___
#define ___INANITY_INANITY_BASE_HPP___

// сборный файл для библиотеки inanity-base

#include "Base64OutputStream.hpp"
#include "BlobFileSystem.hpp"
#include "BlobFileSystemBuilder.hpp"
#include "BufferedFileSystem.hpp"
#include "BufferedInputStream.hpp"
#include "BufferedOutputStream.hpp"
#include "CompositeFileSystem.hpp"
#include "CriticalCode.hpp"
#include "CriticalSection.hpp"
#include "DiskInputStream.hpp"
#include "DiskOutputStream.hpp"
#include "EmptyFile.hpp"
#include "Exception.hpp"
#include "File.hpp"
#include "FileInputStream.hpp"
#include "FileSystem.hpp"
#include "FilterFileSystem.hpp"
#include "FolderFile.hpp"
#include "FolderFileSystem.hpp"
#include "Handle.hpp"
#include "Handler.hpp"
#include "ManagedHeap.hpp"
#include "MemoryFile.hpp"
#include "MemoryStream.hpp"
#include "Object.hpp"
#include "Out2InStream.hpp"
#include "OutputStream.hpp"
#include "PartFile.hpp"
#include "Profiling.hpp"
#include "ResourceManager.ipp"
#include "SafeObject.hpp"
#include "Semaphore.hpp"
#include "StreamReader.hpp"
#include "StreamWriter.hpp"
#include "String.hpp"
#include "StringTraveler.hpp"
#include "Strings.hpp"
#include "TempFileSystem.hpp"
#include "Thread.hpp"
#include "Ticker.hpp"
#include "Time.hpp"

#endif
