#ifndef ___INANITY_INANITY_GRAPHICS_HPP___
#define ___INANITY_INANITY_GRAPHICS_HPP___

/* Общая графика.
 */

#include "Object.hpp"

#include "graphics/graphics.hpp"
#include "graphics/Adapter.hpp"
#include "graphics/AttributeBinding.hpp"
#include "graphics/AttributeLayout.hpp"
#include "graphics/AttributeLayoutElement.hpp"
#include "graphics/AttributeLayoutSlot.hpp"
#include "graphics/BlendState.hpp"
#include "graphics/BmpImage.hpp"
#include "graphics/Context.hpp"
#include "graphics/DataType.hpp"
#include "graphics/DepthStencilBuffer.hpp"
#include "graphics/DepthStencilState.hpp"
#include "graphics/Device.hpp"
#include "graphics/EditableGeometry.hpp"
#include "graphics/FrameBuffer.hpp"
#include "graphics/ImageLoader.hpp"
#include "graphics/IndexBuffer.hpp"
#include "graphics/LayoutDataType.hpp"
#include "graphics/Monitor.hpp"
#include "graphics/MonitorMode.hpp"
#include "graphics/PixelFormat.hpp"
#include "graphics/PixelShader.hpp"
#include "graphics/PngImageLoader.hpp"
#include "graphics/Presenter.hpp"
#include "graphics/RawTextureData.hpp"
#include "graphics/RenderBuffer.hpp"
#include "graphics/RenderStage.hpp"
#include "graphics/SamplerSettings.hpp"
#include "graphics/SamplerState.hpp"
#include "graphics/ShaderCache.hpp"
#include "graphics/ShaderCompiler.hpp"
#include "graphics/ShaderSource.hpp"
#include "graphics/System.hpp"
#include "graphics/SystemSettings.hpp"
#include "graphics/Texture.hpp"
#include "graphics/TextureManager.hpp"
#include "graphics/UniformBuffer.hpp"
#include "graphics/VertexBuffer.hpp"
#include "graphics/VertexLayout.hpp"
#include "graphics/VertexLayoutElement.hpp"
#include "graphics/VertexShader.hpp"

#endif
