#ifndef ___INANITY_INANITY_GUI_HPP___
#define ___INANITY_INANITY_GUI_HPP___

#include "gui/gui.hpp"
#include "gui/Button.hpp"
#include "gui/Canvas.hpp"
#include "gui/ContainerElement.hpp"
#include "gui/Element.hpp"
#include "gui/Font.hpp"
#include "gui/FontEngine.hpp"
#include "gui/FontFace.hpp"
#include "gui/FontGlyphs.hpp"
#include "gui/FontShape.hpp"
#include "gui/FreeContainer.hpp"
#include "gui/ft.hpp"
#include "gui/FtEngine.hpp"
#include "gui/FtFontFace.hpp"
#include "gui/GrCanvas.hpp"
#include "gui/GrFontGlyphs.hpp"
#include "gui/hb.hpp"
#include "gui/HbFontShape.hpp"
#include "gui/Label.hpp"
#include "gui/Notifications.hpp"
#include "gui/Notificator.hpp"
#include "gui/SwCanvas.hpp"
#include "gui/SwFontGlyphs.hpp"
#include "gui/TextBox.hpp"
#include "gui/types.hpp"
#include "gui/Visualizer.hpp"
#include "gui/Visuals.hpp"

#endif
